### ISSUE TITLE
All medicine tick boxes get ticked on submission

### ISSUE THREAD

**Issue by James-Quigley** [2017-Arizona-Opportunity-Hack/Team5#4]
When you submit an administration of a prescription, all the tick boxes get ticked, even if you didn't touch that prescription.

**Comment by TheWiselyBearded** [comment]
Fixed it :D

**Comment by James-Quigley** [comment]
Let's not close issues until the fix is in master. Not sure where the code is that fixed this.

**Comment by TheWiselyBearded** [comment]
Code is in the Parent Components. Previously the Vue-Show boolean was globally shared amongst all Medicine Cards using a V-For loop. So when you clicked one checkmark, all get checked because they share the same bool value. To fix this, I changed all Medicine Cards to be their own components, therefore each of them have their own respective bool attribute to toggle between "+" and "√".
